version: '2'

services:
  nginx:
    image: blacklabelops/nginx:${ATLASSIAN_NGINX_VERSION}
    ports:
      - '443:443'
      - '80:80'
    networks:
      default:
        aliases:
          - '${CONFLUENCE_DOMAIN_NAME}'
          - '${CROWD_DOMAIN_NAME}'
          - '${BITBUCKET_DOMAIN_NAME}'
          - '${JIRA_DOMAIN_NAME}'
    volumes:
      - nginx_volume:/home/nginx
      - ssl_certificates:/etc/letsencrypt
    environment:
      - 'TZ=${ATLASSIAN_TIME_ZONE}'
      - 'NGINX_REDIRECT_PORT80=${ATLASSIAN_PORT80_REDIRECT}'
      - 'SERVER1SERVER_NAME=${JIRA_DOMAIN_NAME}'
      - 'SERVER1REVERSE_PROXY_LOCATION1=/'
      - 'SERVER1REVERSE_PROXY_PASS1=http://jira:8080'
      - 'SERVER1HTTPS_ENABLED=${ATLASSIAN_HTTPS}'
      - 'SERVER1HTTP_ENABLED=${ATLASSIAN_HTTP}'
      - 'SERVER1LETSENCRYPT_CERTIFICATES=${ATLASSIAN_HTTPS}'
      - 'SERVER1CERTIFICATE_FILE=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER1CERTIFICATE_KEY=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/privkey.pem'
      - 'SERVER1CERTIFICATE_TRUSTED=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER1PROXY_APPLICATION=jira'
    
      - 'SERVER3SERVER_NAME=${CONFLUENCE_DOMAIN_NAME}'
      - 'SERVER3REVERSE_PROXY_LOCATION1=/synchrony'
      - 'SERVER3REVERSE_PROXY_PASS1=http://confluence:8091'
      - 'SERVER3REVERSE_PROXY_APPLICATION1=confluence6'
      - 'SERVER3REVERSE_PROXY_LOCATION2=/'
      - 'SERVER3REVERSE_PROXY_PASS2=http://confluence:8090'
      - 'SERVER3REVERSE_PROXY_APPLICATION2=confluence'
      - 'SERVER3HTTPS_ENABLED=${ATLASSIAN_HTTPS}'
      - 'SERVER3HTTP_ENABLED=${ATLASSIAN_HTTP}'
      - 'SERVER3LETSENCRYPT_CERTIFICATES=${ATLASSIAN_HTTPS}'
      - 'SERVER3CERTIFICATE_FILE=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER3CERTIFICATE_KEY=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/privkey.pem'
      - 'SERVER3CERTIFICATE_TRUSTED=/etc/letsencrypt/live/${JIRA_DOMAIN_NAME}/fullchain.pem'
      - 'SERVER3PROXY_APPLICATION=confluence'
     
    restart: unless-stopped
	
  jira_postgresql:
    image: blacklabelops/postgres:${ATLASSIAN_POSTGRES_VERSION}
    hostname: jira_postgresql
    volumes:
      - jira_postgresql_volume:/var/lib/postgresql/data
    environment:
      - 'TZ=${ATLASSIAN_TIME_ZONE}'
      - 'POSTGRES_DB=atlassiandb'
      - 'POSTGRES_USER=${ATLASSIAN_DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${ATLASSIAN_DB_PASSWORD}'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    restart: unless-stopped
	
  jira:
    image: blacklabelops/jira:${JIRA_VERSION}
    hostname: jira
    volumes:
      - jira_volume:/var/atlassian/jira
    environment:
      - 'TZ=${ATLASSIAN_TIME_ZONE}'
      - "CATALINA_OPTS=${JIRA_JAVA_OPTIONS}"
      - "JIRA_PROXY_NAME=${JIRA_DOMAIN_NAME}"
      - "JIRA_PROXY_PORT=${ATLASSIAN_PROXY_PORT}"
      - "JIRA_PROXY_SCHEME=${ATLASSIAN_PROXY_SCHEME}"
      - 'JIRA_DATABASE_URL=postgresql://${ATLASSIAN_DB_USERNAME}@jira_postgresql/atlassiandb'
      - 'JIRA_DB_PASSWORD=${ATLASSIAN_DB_PASSWORD}'
      - 'JIRA_DELAYED_START=${ATLASSIAN_DB_DELAYED_START}'
    restart: unless-stopped 
	
  confluence_postgresql:
    image: blacklabelops/postgres:${ATLASSIAN_POSTGRES_VERSION}
    hostname: confluence_postgresql
    volumes:
      - confluence_postgresql_volume:/var/lib/postgresql
    environment:
      - 'TZ=${ATLASSIAN_TIME_ZONE}'
      - 'POSTGRES_DB=atlassiandb'
      - 'POSTGRES_USER=${ATLASSIAN_DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${ATLASSIAN_DB_PASSWORD}'
    restart: unless-stopped
	
  confluence:
    image: blacklabelops/confluence:${CONFLUENCE_VERSION}
    hostname: confluence
    volumes:
      - confluence_volume:/var/atlassian/confluence
    environment:
      - 'TZ=${ATLASSIAN_TIME_ZONE}'
      - "CATALINA_OPTS=${CONFLUENCE_JAVA_OPTIONS}"
      - "CONFLUENCE_PROXY_NAME=${CONFLUENCE_DOMAIN_NAME}"
      - "CONFLUENCE_PROXY_PORT=${ATLASSIAN_PROXY_PORT}"
      - "CONFLUENCE_PROXY_SCHEME=${ATLASSIAN_PROXY_SCHEME}"
    restart: unless-stopped  

volumes:
  nginx_volume:
    external: false
  ssl_certificates:
    external: false
  jira_postgresql_volume:
    external: false
  jira_volume:
    external: false
  crowd_postgresql_volume:
    external: false
  crowd_volume:
    external: false
  confluence_postgresql_volume:
    external: false
  confluence_volume:
    external: false
  bitbucket_postgresql_volume:
    external: false
  bitbucket_volume:
    external: false
